### ISSUE TITLE
Checking if an email address exists 

### ISSUE THREAD

**Issue by qadeemakhtar** [pmengal/MailSystem.NET#7]
Hi!
I want to check an email Address actually Exist or not. 
I tried this function but it return false  every time even my own Email Address .

ActiveUp.Net.Mail.SmtpClient aa = new ActiveUp.Net.Mail.SmtpClient();
            bool isEmailExist=aa.Verify("qadeemakhtar@hotmail.com");

**Comment by reinaldocoelho** [comment]
Hi @qadeemakhtar , the MailSystem uses the SMTP command "VRFY(https://cr.yp.to/smtp/vrfy.html)" to verify the e-mail.

Are you shure the mail server accepts the command?

If you shure, can you verify if this works on a free e-mail like Gmail or Hotmail and return to me?

Thanks.

**Comment by qadeemakhtar** [comment]
@reinaldocoelho  I checked it with Gmail and Hotmail email addresses but it always return me null.

**Comment by reinaldocoelho** [comment]
@qadeemakhtar, I checked the reason for the non-functioning of the VRFY command in Gmail and Hotmail.

During the research I identified that the vast majority of e-mail servers are shutting down the command for exposing users informations and be considered a security flaw.

With this function disabled, your answer will always be false.

Unfortunately I do not have access to any SMTP server with this active command to validate, but I believe your problem is this, your SMTP provider probably is not releasing the command.

My suggestion is for you to check availability with the responsibility for the SMTP server.

I have helped.
